name: CI

on: [ push, pull_request ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: bda_py_demos
          environment-file: environment.yml
          channels: conda-forge,defaults

      - name: Cache conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg

      - name: Install extra test dependencies
        shell: bash -l {0}
        run: |
          conda install -y pytest pytest-xdist nbval

      - name: Run tests
        shell: bash -l {0}
        run: pytest -n 2 --junitxml=test_report.xml --nbval-lax . --dist loadscope

      - name: Upload test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ./test_report.xml
          check_name: Test results
